# Default sett
# https://github.com/jwilm/alacritty/blob/dea7a0890a724c50bc5767039f45a2e3d071ee1c/alacritty.yml

#env:
  #TERM: xterm-256color-italic

window:
  decorations: full
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Operator Mono SSm
    style: Book

  bold:
    family: Operator Mono SSm
    style: Medium

  bold_italic:
    family: Operator Mono SSm
    style: Medium Italic

  italic:
    family: Operator Mono SSm
    style: Book Italic

  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 6

# Colors (Tomorrow Night Bright)
# Colors (One Dark)
# https://github.com/jwilm/alacritty/wiki/Color-schemes
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '0x131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '#333333'
    red:     '#f2777a'
    green:   '#99cc99'
    yellow:  '#ffcc66'
    blue:    '#6699cc'
    magenta: '#cc99cc'
    cyan:    '#66cccc'
    white:   '#dddddd'

shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - 'tmux attach -t TMUX || tmux new -s TMUX'

key_bindings:
- { key: H,         mods: Command,      action: None                  }
- { key: M,         mods: Command,      action: None                  }
- { key: Q,         mods: Command,      action: None                  }
- { key: Space,     mods: Alt,          chars: " "                    }
- { key: Space,     mods: Alt,          chars: " "                    }

#   # Map ctrl + space tmux prefix (github.com/jwilm/alacritty/issues/99)
- { key: Space,     mods: Control,      chars: "\x00"                 }
